# This is a basic workflow to help you get started with Actions

name: Check_Broken_VIs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.drawio'
      - '**.vipb'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Check_Broken_VIs:
    # The type of runner that the job will run on
    runs-on: [self-hosted, lv2020]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4.1.1

      - name: install NEVSTOP-Programming-Palette
        uses: NEVSTOP-LAB/InstallNevstopPackage@main
        with:
          LabVIEW_Version: 2020
          NEVSTOP-FTP-IP: ${{ secrets.VIPM_FTP_IP }}
          NEVSTOP-FTP-PORT: ${{ secrets.VIPM_FTP_PORT }}
          PackageName: NEVSTOP-Programming-Palette
          PackageName1: Communicable-State-Machine
          PackageName2: CSM-API-String-Arguments-Support

      - name: vipm-InstallPackage
        uses: NEVSTOP-LAB/vipm-InstallPackage@main
        with:
          LabVIEW_Version: 2020
          # Package could be PackageName/PacakgeWithVersion/vipFilePath
          Package: "NI String Tools Library"

      # Runs a set of commands using the runners shell
      - id: Check_Broken_VIs
        uses: LV-APT/lvCICD@main
        with:
          LabVIEW_Version: 2020
          Operation: VIAn_CheckBrokenVIs
          Parameter1: ${{ github.workspace }}
          Parameter2: NOPASSWORD
          Parameter3: YES
          Parameter4: -placeContent
